-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgdwV+7Ml5RFPCFbyC
teHj3/Zb2ZDNT1F5cT8FQ3eiPxigCgYIKoZIzj0DAQehRANCAASFf8VVPs46O2u6
lzExlOkgBtlD7sghMQbIFDVch9N0IUQDqfQbUa7SKojDDixLSgbaQUuPOtGwtkoK
+5LkyL1i
-----END PRIVATE KEY-----