spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gguro
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: false
        use_sql_comments: false
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

jwt:
  header: Authorization
  secret: ${JWT_SECRET}

apple:
  client-id: ${APPLE_CLIENT_ID}
  team-id: G8X4BWGTSS
  key-id: 5M442V5A32
  private-key-path: classpath:keys/apple-private-key.p8
  audience: https://appleid.apple.com
  grant-type: authorization_code
  redirect-uri: https://gguro.store/api/auth/apple

server:
  port: 443
  ssl:
    enabled: true
    key-store: /opt/gguro/keystore.p12
    key-store-password: gguro1234
    key-store-type: PKCS12
    key-alias: springboot-cert

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: gguro-bucket
    stack:
      auto: false
    path:
      profile-image: profile
